### ISSUE TITLE
Error messages in the PENCIL runtime

### ISSUE THREAD

**Issue by rbaghdadi** [carpproject/pencil-util#7]
Hi,

I tried the PENCIL runtime during this week.  It worked correctly and
smoothly for me.

I want to ask for adding support for showing OpenCL error messages in
the runtime.  Currently in case of an error only the error number is
printed which does not tell the user anything about the nature of the
problem.

**Comment by carpproject** [comment]
I have pushed the change to make the runtime print OpenCL errors similar to the original method used in the  PPCG (it uses the same function from ocl_utilities).

Please check whether this change works for you.

**Comment by rbaghdadi** [comment]
Perfect thanks.
